# example

# settings for gloabl use
settings: 
  telegram_bot_token: ${{TELEGRAM_BOT_TOKEN}} # string variables in ${{...}} are parsed from environment 
  telegram_chats:
    - 111111111
    - "-12345678"

  smtp_host: smtp.example.com
  smtp_port: 425 # if not defined - 25 is default
  smtp_username: smtp_admin # if username and password not defined - will try to proceed without authentication
  smtp_password: ${{SMTP_PASSWORD}} 
  smtp_from: pingo@example.com
  smtp_recipients:
    - cto@example.com
    - sysadmins@example.com


# list of jobs
jobs:

  an-important-service: # name of your job, used in alerts
    type: endpoint-health # type of your job
    group: production   # jobs are ordered by group
    endpoint: https://important.example.org/ping # endpoint, that is going to be requested for healthcheck
    interval: 10s # interval for a job. Expect string as for https://pkg.go.dev/time#ParseDuration 
    on_failure: # tasks to execute on failures
      - telegram-alert # send telegram message with bot token and chat 
      - email-alert # send email message 
    on_recovery: # tasks to execute on recovery (change status task from failed to success)
      - telegram-alert

  local-memory-check:
    type: ram-usage # check current ram usage
    group: local
    threshold: 0.9 # threshold for failing - current ram usage / total ram usage
    interval: 10s
    on_failure:
      - telegram-alert
    on_recovery:
      - telegram-alert

  local-disk-check:
    type: disk-usage
    threshold: 0.8 # threshold for failing - current disk usage / total size
    interval: 10s
    path: / # path for disk usage
    on_failure:
      - telegram-alert
    on_recovery:
      - telegram-alert
